affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda:0
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 3
symbolic.funs_name.0:
- - sin
  - exp
  - sin
  - sin
- - x
  - sin
  - sin
  - sin
- - exp
  - x
  - sqrt
  - x
- - x
  - x
  - x
  - x
- - sin
  - x
  - sin
  - sin
- - x
  - x
  - x
  - sin
symbolic.funs_name.1:
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
symbolic.funs_name.2:
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 4
  - 0
- - 0
  - 3
- - 5
  - 0
- - 7
  - 0
